inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true

Layout/IndentHeredoc:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - '*.gemspec'

Naming/HeredocDelimiterNaming:
  Enabled: false
